# fmt: off
"""Kapitel 1-5 Seed-Daten."""
CHAPTERS_1_5 = [
{
"title": "Die unsichtbare Verschiebung",
"description": "Shadow AI erkennen, Entscheidungsarchitektur verstehen, KI-Souver\u00e4nit\u00e4t aufbauen.",
"ordering": 1,
"lessons": [
{"title": "Shadow AI erkennen", "ordering": 1, "duration": 5, "content":
"# Shadow AI erkennen\n\n"
"Shadow AI bezeichnet den Einsatz von KI-Tools durch Mitarbeitende, "
"der ohne offizielle Freigabe, Dokumentation oder Governance stattfindet.\n\n"
"## Das Eisberg-Modell\n\n"
"Etwa **70\u201380 %** der tats\u00e4chlichen KI-Nutzung in Unternehmen ist Shadow AI.\n\n"
"### Sichtbar\n"
"- Offiziell beschaffte KI-Tools\n"
"- IT-genehmigte Lizenzen\n"
"- Dokumentierte Prozesse\n\n"
"### Unsichtbar\n"
"- ChatGPT \u00fcber private Accounts\n"
"- KI-Funktionen in bestehenden SaaS-Tools\n"
"- Externe Dienstleister mit KI-Einsatz\n"
"- Browser-Erweiterungen mit KI\n"
"- Automatische KI-Features in Office-Produkten\n\n"
"## Warum Shadow AI gef\u00e4hrlich ist\n\n"
"1. **Datenschutz**: Vertrauliche Daten flie\u00dfen in externe KI-Systeme\n"
"2. **Compliance**: Keine Dokumentation = keine Nachweisbarkeit (EU AI Act)\n"
"3. **Qualit\u00e4t**: Unkontrollierte Outputs beeinflussen Gesch\u00e4ftsentscheidungen\n"
"4. **Haftung**: Wer haftet f\u00fcr KI-gest\u00fctzte Fehlentscheidungen?\n\n"
"## 5-Punkte Shadow-AI-Inventur\n\n"
"1. Fragen Sie in jeder Abteilung: *\u201eWelche KI-Tools nutzt ihr?\u201c*\n"
"2. Pr\u00fcfen Sie Ihre SaaS-Vertr\u00e4ge auf aktivierte KI-Funktionen\n"
"3. Fragen Sie externe Dienstleister\n"
"4. Analysieren Sie Ihren Tech-Stack\n"
"5. Etablieren Sie ein monatliches 15-Minuten-Update\n\n"
"> **Merksatz:** 76 % der deutschen KMU setzen KI ein \u2014 aber nur 24 % wissen, welche.\n"
},
{"title": "Entscheidungsarchitektur unter KI-Einfluss", "ordering": 2, "duration": 8, "content":
"# Entscheidungsarchitektur unter KI-Einfluss\n\n"
"Jede Organisation hat eine Entscheidungsarchitektur. KI ver\u00e4ndert diese fundamental.\n\n"
"## Drei Ebenen der Ver\u00e4nderung\n\n"
"### 1. Informationsebene\n"
"KI filtert und priorisiert Informationen, bevor sie den Entscheider erreichen.\n\n"
"- **Vorher:** Manager sichtet 20 Bewerbungen selbst\n"
"- **Nachher:** KI-Screening zeigt \u201eTop 5\u201c \u2014 die anderen 15 sieht niemand\n\n"
"### 2. Bewertungsebene\n"
"KI liefert Empfehlungen und Scores, die als Anker wirken.\n\n"
"- **Vorher:** Vertriebsteam sch\u00e4tzt Kundenrisiko aus Erfahrung\n"
"- **Nachher:** CRM zeigt \u201eChurn-Wahrscheinlichkeit 78 %\u201c\n\n"
"### 3. Ausf\u00fchrungsebene\n"
"KI automatisiert Teilentscheidungen ohne menschliche Pr\u00fcfung.\n\n"
"- **Vorher:** Jede Preisanpassung wird freigegeben\n"
"- **Nachher:** Dynamic Pricing passt Preise in Echtzeit an\n\n"
"## Handlungsempfehlungen\n\n"
"1. **Kartieren** Sie Ihre Entscheidungsprozesse\n"
"2. **Kennzeichnen** Sie KI-gest\u00fctzte Empfehlungen\n"
"3. **Definieren** Sie, welche Entscheidungen *immer* menschlich bleiben\n"
"4. **Dokumentieren** Sie, wenn KI-Empfehlungen \u00fcberstimmt werden\n"
},
{"title": "KI-Souver\u00e4nit\u00e4t: Was es bedeutet, souver\u00e4n zu entscheiden", "ordering": 3, "duration": 6, "content":
"# KI-Souver\u00e4nit\u00e4t: Souver\u00e4n entscheiden\n\n"
"KI-Souver\u00e4nit\u00e4t ist die F\u00e4higkeit, KI bewusst, kontrolliert und "
"selbstbestimmt einzusetzen \u2014 ohne die Entscheidungshoheit abzugeben.\n\n"
"## Die vier S\u00e4ulen\n\n"
"### Durchblicken (Transparenz)\n"
"Wissen, welche KI-Systeme im Einsatz sind und wie sie wirken.\n\n"
"### Durchsetzen (Governance)\n"
"Klare Richtlinien, Verantwortlichkeiten, Freigabeprozesse.\n\n"
"### Durchf\u00fchren (Umsetzung)\n"
"KI-Projekte strukturiert planen, Pilotphasen, Change Management.\n\n"
"### Durchhalten (Nachhaltigkeit)\n"
"Regelm\u00e4\u00dfige Reviews, Monitoring, kontinuierliche Weiterbildung.\n\n"
"## Von Kontrolle zu Gestaltung\n\n"
"| Unsouver\u00e4n | Souver\u00e4n |\n"
"|-----------|----------|\n"
"| \u201eWir nutzen halt ChatGPT\u201c | \u201eWir haben definiert, wof\u00fcr\u201c |\n"
"| \u201eDie IT k\u00fcmmert sich\u201c | \u201eKI-Governance ist Chefsache\u201c |\n"
"| \u201eWir machen das irgendwann\u201c | \u201eWir haben einen 90-Tage-Plan\u201c |\n\n"
"> **Kernthese:** Nicht KI ist das Problem \u2014 sondern die Illusion, ohne KI zu entscheiden.\n"
},
],
},
{
"title": "Was Maschinen nicht wissen \u2014 und Manager nicht mehr",
"description": "Selbstbild, kognitive Fallen und Gegenstrategien.",
"ordering": 2,
"lessons": [
{"title": "Das ver\u00e4nderte Selbstbild des Entscheiders", "ordering": 1, "duration": 6, "content":
"# Das ver\u00e4nderte Selbstbild des Entscheiders\n\n"
"## Die drei Identit\u00e4tskrisen\n\n"
"### 1. Der Experte wird zum Laien\n"
"KI erkennt Hautkrebs mit 95 % \u2014 der Chefarzt liegt bei 87 %.\n\n"
"### 2. Der Entscheider wird zum Best\u00e4tiger\n"
"Statt eigenst\u00e4ndig zu entscheiden, best\u00e4tigen F\u00fchrungskr\u00e4fte KI-Empfehlungen.\n\n"
"### 3. Der Stratege wird zum Operator\n"
"Weniger Strategie, mehr Verwaltung von KI-Systemen.\n\n"
"## Wie Sie Ihre Rolle neu definieren\n\n"
"1. **Kontextwissen:** KI kennt Daten, Sie kennen den Kontext\n"
"2. **Werteentscheidungen:** KI optimiert Metriken, Sie entscheiden \u00fcber Werte\n"
"3. **Beziehungsarbeit:** KI analysiert Kunden, Sie pflegen Beziehungen\n"
"4. **Verantwortung:** KI empfiehlt, Sie verantworten\n\n"
"> **Merksatz:** Welche Frage stellt die KI \u2014 und welche stellt sie nicht?\n"
},
{"title": "Kognitive Fallen im KI-Zeitalter", "ordering": 2, "duration": 8, "content":
"# Kognitive Fallen im KI-Zeitalter\n\n"
"## Die f\u00fcnf gef\u00e4hrlichsten KI-Fallen\n\n"
"### 1. Automation Bias\n"
"Algorithmischen Empfehlungen blind vertrauen.\n"
"**Gegen:** Red Team \u2014 mindestens eine Person hinterfragt systematisch.\n\n"
"### 2. Algorithm Aversion\n"
"KI irrational ablehnen, selbst wenn sie besser ist.\n"
"**Gegen:** KI als zweite Meinung, nicht als Ersatz.\n\n"
"### 3. Anchoring durch KI\n"
"KI-Outputs setzen den Referenzpunkt f\u00fcr alle weiteren \u00dcberlegungen.\n"
"**Gegen:** Eigene Einsch\u00e4tzung *vor* dem KI-Output bilden.\n\n"
"### 4. Confirmation Bias 2.0\n"
"KI best\u00e4tigt vorhandene \u00dcberzeugungen (historische Daten).\n\n"
"### 5. Illusion of Understanding\n"
"ChatGPT formuliert \u00fcberzeugend \u2014 also inhaltlich richtig?\n"
"**Gegen:** *Darstellungsqualit\u00e4t* und *inhaltliche Qualit\u00e4t* unterscheiden.\n"
},
{"title": "Urteilsst\u00e4rke bewahren: Gegenstrategien", "ordering": 3, "duration": 7, "content":
"# Urteilsst\u00e4rke bewahren\n\n"
"## Die 5 Gegenstrategien\n\n"
"### 1. Die Vorab-Hypothese\n"
"Eigene Einsch\u00e4tzung *vor* dem KI-Output. Aufschreiben. Dann vergleichen.\n\n"
"### 2. Das Advocatus-Diaboli-Prinzip\n"
"Rotierendes Red Team: *Warum k\u00f6nnte die KI hier falsch liegen?*\n\n"
"### 3. Die Grenzziehung\n"
"Welche Entscheidungen *nie* an KI delegieren?\n"
"- K\u00fcndigungen und Einstellungen\n"
"- Strategische Neuausrichtungen\n"
"- Ethisch sensible Kundenentscheidungen\n\n"
"### 4. Der Reflexionsrhythmus\n"
"Monats-Review (15 Min.): Was \u00fcbernommen? Was \u00fcberstimmt? Was gelernt?\n\n"
"### 5. Die Kompetenz-Investition\n"
"Grundlogik verstehen: Welche Daten? Welche Annahmen? Welche Grenzen?\n\n"
"> **Kernthese:** Urteilsst\u00e4rke ist kein Talent \u2014 sie ist eine Praxis.\n"
},
],
},
{
"title": "Regulierung als Chance \u2014 Der EU AI Act f\u00fcr Praktiker",
"description": "Risikoklassen, Art. 4 KI-Kompetenz, 90-Tage-Aktionsplan.",
"ordering": 3,
"lessons": [
{"title": "EU AI Act: Die Risikoklassen verstehen", "ordering": 1, "duration": 7, "content":
"# EU AI Act: Die Risikoklassen\n\n"
"## Die vier Risikoklassen\n\n"
"### Minimales Risiko (keine Pflichten)\n"
"Spam-Filter, KI in Videospielen, Empfehlungssysteme\n\n"
"### Begrenztes Risiko (Transparenzpflichten)\n"
"Chatbots, Deepfakes \u2014 m\u00fcssen als KI gekennzeichnet werden\n\n"
"### Hohes Risiko (umfassende Pflichten)\n"
"Personalauswahl, Kreditvergabe, Bildung, kritische Infrastruktur\n\n"
"**Pflichten:** Risikomanagement, Datenqualit\u00e4t, Dokumentation, "
"menschliche Aufsicht, Logging\n\n"
"### Unakzeptables Risiko (verboten)\n"
"Social Scoring, Manipulation, biometrische Echtzeit-\u00dcberwachung\n\n"
"## Timeline\n\n"
"| Datum | Was passiert |\n"
"|-------|-------------|\n"
"| **Feb 2025** | Verbotene KI-Praktiken gelten |\n"
"| **Feb 2026** | Art. 4 KI-Kompetenzpflicht gilt |\n"
"| **Aug 2026** | Hochrisiko-Pflichten vollst\u00e4ndig |\n\n"
"## Bu\u00dfgelder\n"
"- Verbotene KI: bis **35 Mio. \u20ac** oder 7 % Jahresumsatz\n"
"- Hochrisiko-Verst\u00f6\u00dfe: bis **15 Mio. \u20ac** oder 3 % Jahresumsatz\n\n"
"> Art. 4 gilt bereits \u2014 f\u00fcr *jedes* Unternehmen, das KI einsetzt.\n"
},
{"title": "Artikel 4: KI-Kompetenzpflicht umsetzen", "ordering": 2, "duration": 8, "content":
"# Artikel 4: KI-Kompetenzpflicht\n\n"
"## Drei Lernpfade nach Rolle\n\n"
"### Gesch\u00e4ftsf\u00fchrung (4\u20136 Stunden)\n"
"KI-Strategie, Governance, Risikoklassen, Haftung\n\n"
"### IT-Leitung / DSB (8\u201312 Stunden)\n"
"Technische Bewertung, Datenschutz, Monitoring, Vendor-Management\n\n"
"### Fachabteilung (2\u20133 Stunden)\n"
"Sichere KI-Nutzung, Grenzen, Meldepflichten\n\n"
"## Compliance-Checkliste\n\n"
"- [ ] Rollenbezogene Schulungskonzepte?\n"
"- [ ] Nachweisbare Lernergebnisse?\n"
"- [ ] Onboarding f\u00fcr neue Mitarbeiter?\n"
"- [ ] J\u00e4hrlicher Refresher?\n"
"- [ ] Revisionssichere Dokumentation?\n\n"
"> Art. 4 verlangt Kompetenz, nicht Compliance.\n"
},
{"title": "Von der Pflicht zum Plan: 90-Tage-Aktionsplan", "ordering": 3, "duration": 8, "content":
"# 90-Tage-Aktionsplan\n\n"
"## Phase 1: Bestandsaufnahme (Tag 1\u201330)\n"
"1. KI-Inventar erstellen\n"
"2. Risikoklassen zuordnen\n"
"3. Verantwortlichkeiten kl\u00e4ren\n"
"4. L\u00fccken identifizieren\n"
"\u2192 **Ergebnis:** KI-Register mit Risikoklassifizierung\n\n"
"## Phase 2: Governance aufbauen (Tag 31\u201360)\n"
"1. KI-Nutzungsrichtlinie erstellen\n"
"2. Verantwortlichen benennen\n"
"3. Freigabeprozess definieren\n"
"4. Schulungskonzept entwickeln\n"
"\u2192 **Ergebnis:** KI-Governance-Rahmen\n\n"
"## Phase 3: Umsetzung starten (Tag 61\u201390)\n"
"1. Pilotschulungen durchf\u00fchren\n"
"2. Hochrisiko-Systeme dokumentieren\n"
"3. Quick Wins umsetzen\n"
"4. Review-Termin f\u00fcr Tag 180 setzen\n"
"\u2192 **Ergebnis:** Laufende Compliance-Ma\u00dfnahmen\n\n"
"> Der EU AI Act ist eine Chance, nicht ein B\u00fcrokratie-Monster.\n"
},
],
},
{
"title": "Das D4-Modell \u2014 Vier Dimensionen der KI-Souver\u00e4nit\u00e4t",
"description": "Durchblicken, Durchsetzen, Durchf\u00fchren, Durchhalten \u2014 das Reifegradmodell.",
"ordering": 4,
"lessons": [
{"title": "Durchblicken & Durchsetzen", "ordering": 1, "duration": 8, "content":
"# Durchblicken & Durchsetzen\n\n"
"## Dimension 1: Durchblicken (Transparenz)\n\n"
"| Stufe | Name | Beschreibung |\n"
"|-------|------|-------------|\n"
"| 1 | Unbewusst | Keine \u00dcbersicht \u00fcber KI-Nutzung |\n"
"| 2 | Erkennend | Erste Inventarisierung |\n"
"| 3 | Systematisch | Vollst\u00e4ndiges KI-Register |\n"
"| 4 | Analytisch | Wirkungsanalyse f\u00fcr alle Systeme |\n"
"| 5 | Souver\u00e4n | Echtzeit-Monitoring |\n\n"
"**Stufenplan:** Shadow-AI-Inventur \u2192 KI-Register \u2192 Impact-Assessment \u2192 Dashboard\n\n"
"## Dimension 2: Durchsetzen (Governance)\n\n"
"| Stufe | Name | Beschreibung |\n"
"|-------|------|-------------|\n"
"| 1 | Regellos | Keine KI-Richtlinien |\n"
"| 2 | Informell | M\u00fcndliche Absprachen |\n"
"| 3 | Dokumentiert | Schriftliche Richtlinie |\n"
"| 4 | Durchgesetzt | Freigabeprozess + Monitoring |\n"
"| 5 | Adaptiv | Selbstlernende Governance |\n\n"
"**Stufenplan:** Do's & Don'ts \u2192 Richtlinie \u2192 Freigabeprozess \u2192 Quartals-Review\n"
},
{"title": "Durchf\u00fchren & Durchhalten", "ordering": 2, "duration": 8, "content":
"# Durchf\u00fchren & Durchhalten\n\n"
"## Dimension 3: Durchf\u00fchren (Umsetzung)\n\n"
"| Stufe | Name | Beschreibung |\n"
"|-------|------|-------------|\n"
"| 1 | Ad hoc | KI-Nutzung zuf\u00e4llig |\n"
"| 2 | Pilotierend | Erste Pilotprojekte |\n"
"| 3 | Standardisiert | Einheitlicher Prozess |\n"
"| 4 | Optimiert | Lessons Learned flie\u00dfen zur\u00fcck |\n"
"| 5 | Innovativ | Proaktive KI-Innovation |\n\n"
"### KI-Projekt-Checkliste\n"
"1. Business Case: Welches Problem l\u00f6st die KI?\n"
"2. Datenqualit\u00e4t: Geeignete Daten vorhanden?\n"
"3. Risikoklasse: EU AI Act-Einordnung\n"
"4. Pilotphase: 4\u20138 Wochen mit KPIs\n"
"5. Change Management: Schulung + Kommunikation\n\n"
"## Dimension 4: Durchhalten (Nachhaltigkeit)\n\n"
"| Stufe | Name | Beschreibung |\n"
"|-------|------|-------------|\n"
"| 1 | Einmalig | Keine Review-Zyklen |\n"
"| 2 | Reaktiv | Review nur bei Problemen |\n"
"| 3 | Geplant | Quartalsweise Reviews |\n"
"| 4 | Proaktiv | Kontinuierliches Monitoring |\n"
"| 5 | Kulturell | KI-Souver\u00e4nit\u00e4t als Unternehmenskultur |\n\n"
"> Wer nur eine Dimension vernachl\u00e4ssigt, verliert die Kontrolle.\n"
},
{"title": "D4-Selbsteinsch\u00e4tzung", "ordering": 3, "duration": 7, "content":
"# D4-Selbsteinsch\u00e4tzung\n\n"
"Bewerten Sie jede Aussage: **1** (trifft nicht zu) bis **5** (trifft voll zu)\n\n"
"## Durchblicken\n"
"1. Ich kenne alle KI-Systeme im Unternehmen\n"
"2. Ich verstehe, wie sie Entscheidungen beeinflussen\n"
"3. Ich kann erkl\u00e4ren, welche Daten genutzt werden\n"
"4. Ich wei\u00df die Risikoklasse jedes Systems\n"
"5. Mein Team versteht den Unterschied KI-Unterst\u00fctzung vs. KI-Entscheidung\n\n"
"## Durchsetzen\n"
"6. Aktuelle KI-Nutzungsrichtlinie vorhanden\n"
"7. Verantwortlichkeiten klar benannt\n"
"8. Freigabeprozess f\u00fcr neue KI-Tools\n"
"9. DSB in KI-Entscheidungen eingebunden\n"
"10. Dokumentation bei Hochrisiko-Systemen\n\n"
"## Durchf\u00fchren\n"
"11. Klarer Business Case f\u00fcr KI-Projekte\n"
"12. Pilotphasen vor Rollout\n"
"13. Change Management bei KI-Einf\u00fchrung\n"
"14. Erfolgsmessung mit KPIs\n"
"15. Lessons Learned flie\u00dfen zur\u00fcck\n\n"
"## Durchhalten\n"
"16. Regelm\u00e4\u00dfige KI-Reviews\n"
"17. Monitoring f\u00fcr KI-Outputs\n"
"18. J\u00e4hrliche Schulungs-Refresher\n"
"19. KI-Register wird aktualisiert\n"
"20. KI-Souver\u00e4nit\u00e4t ist Teil der Kultur\n\n"
"## Auswertung\n\n"
"| Summe | Reifegrad |\n"
"|-------|----------|\n"
"| 5\u20138 | Stufe 1 \u2014 Unbewusst |\n"
"| 9\u201312 | Stufe 2 \u2014 Erkennend |\n"
"| 13\u201317 | Stufe 3 \u2014 Systematisch |\n"
"| 18\u201322 | Stufe 4 \u2014 Optimiert |\n"
"| 23\u201325 | Stufe 5 \u2014 Souver\u00e4n |\n"
},
],
},
{
"title": "Das R\u00b3-Raster \u2014 Risiken richtig bewerten",
"description": "Recognize, Rate, Respond \u2014 Risikobewertung f\u00fcr jeden KI-Anwendungsfall.",
"ordering": 5,
"lessons": [
{"title": "Recognize \u2014 KI-Risiken erkennen", "ordering": 1, "duration": 7, "content":
"# Recognize \u2014 KI-Risiken erkennen\n\n"
"## Die 6 Risikokategorien\n\n"
"### 1. Datenrisiken\n"
"Personenbezogene Daten, Trainings-Bias, Datenlecks\n\n"
"### 2. Entscheidungsrisiken\n"
"Fehlentscheidungen, Diskriminierung, mangelnde Erkl\u00e4rbarkeit\n\n"
"### 3. Compliance-Risiken\n"
"EU AI Act, DSGVO Art. 22, branchenspezifische Regulierung\n\n"
"### 4. Reputationsrisiken\n"
"KI-Pannen, Halluzinationen, Vertrauensverlust\n\n"
"### 5. Abh\u00e4ngigkeitsrisiken\n"
"Vendor Lock-in, Wissensverlust durch Automatisierung\n\n"
"### 6. Sicherheitsrisiken\n"
"Adversarial Attacks, Prompt Injection, Datenexfiltration\n\n"
"## Erkennungs-Checkliste\n"
"- [ ] Welche Daten flie\u00dfen ein?\n"
"- [ ] Wer hat Zugriff?\n"
"- [ ] Welche Entscheidungen werden beeinflusst?\n"
"- [ ] Was passiert bei Ausfall?\n"
"- [ ] Regulatorische Anforderungen?\n"
},
{"title": "Rate \u2014 Risiken systematisch bewerten", "ordering": 2, "duration": 8, "content":
"# Rate \u2014 Risiken bewerten\n\n"
"## Die Risikomatrix\n\n"
"| | Gering | Mittel | Hoch |\n"
"|---|---|---|---|\n"
"| **Hohe Wahrsch.** | Mittel | Hoch | Kritisch |\n"
"| **Mittlere Wahrsch.** | Niedrig | Mittel | Hoch |\n"
"| **Geringe Wahrsch.** | Niedrig | Niedrig | Mittel |\n\n"
"## Bewertungskriterien\n\n"
"**Auswirkung (1\u20135):** Keine Folgen \u2192 Existenzbedrohend\n\n"
"**Wahrscheinlichkeit (1\u20135):** < 5 % \u2192 > 80 %\n\n"
"## Praxisbeispiel: Bewerber-Screening\n\n"
"| Risiko | Auswirkung | Wahrsch. | Score |\n"
"|--------|-----------|----------|-------|\n"
"| Diskriminierung | 5 | 3 | 15 \u2014 **Kritisch** |\n"
"| DSGVO-Versto\u00df | 4 | 4 | 16 \u2014 **Kritisch** |\n"
"| Fehleinsch\u00e4tzung | 3 | 3 | 9 \u2014 Mittel |\n"
"| Datenleck | 4 | 2 | 8 \u2014 Mittel |\n"
},
{"title": "Respond \u2014 Richtig reagieren", "ordering": 3, "duration": 7, "content":
"# Respond \u2014 Richtig reagieren\n\n"
"## Vier Reaktionsstrategien\n\n"
"### 1. Vermeiden\n"
"KI-System nicht einsetzen, wenn Risiko zu hoch.\n\n"
"### 2. Mitigieren\n"
"Risiko durch Ma\u00dfnahmen senken: Human-in-the-Loop, Bias-Audits, "
"Zugriffsbeschr\u00e4nkungen.\n\n"
"### 3. Transferieren\n"
"Risiko auf Dritte \u00fcbertragen: Versicherung, vertragliche Haftung.\n\n"
"### 4. Akzeptieren\n"
"Bewusst akzeptieren bei niedrigem Restrisiko. Dokumentieren!\n\n"
"## Der Ma\u00dfnahmenplan\n\n"
"F\u00fcr jedes kritische/hohe Risiko:\n"
"1. **Was:** Konkrete Ma\u00dfnahme\n"
"2. **Wer:** Verantwortliche Person\n"
"3. **Bis wann:** Deadline\n"
"4. **Wie messen:** Erfolgskriterium\n"
"5. **Review:** N\u00e4chster Pr\u00fcftermin\n\n"
"> Risikomanagement ist kein Projekt \u2014 es ist ein kontinuierlicher Prozess.\n"
},
],
},
]
# fmt: on
