# fmt: off
"""Kapitel 6-9 Seed-Daten."""
CHAPTERS_6_9 = [
{
"title": "KI-Inventar aufbauen \u2014 Was l\u00e4uft in Ihrem Unternehmen?",
"description": "Systematische Erfassung aller KI-Systeme, Risikoklassifizierung, Verantwortlichkeiten.",
"ordering": 6,
"lessons": [
{"title": "Das KI-Inventar: Methodik und Vorgehen", "ordering": 1, "duration": 7, "content":
"# Das KI-Inventar: Methodik\n\n"
"Ein KI-Inventar ist die Grundlage jeder KI-Governance. Ohne Inventar keine Transparenz, "
"ohne Transparenz keine Souver\u00e4nit\u00e4t.\n\n"
"## Was geh\u00f6rt ins Inventar?\n\n"
"F\u00fcr jedes KI-System erfassen:\n\n"
"| Feld | Beispiel |\n"
"|------|----------|\n"
"| **Name** | Microsoft Copilot |\n"
"| **Anbieter** | Microsoft |\n"
"| **Einsatzbereich** | Office-Produktivit\u00e4t |\n"
"| **Abteilung** | Alle |\n"
"| **Verantwortlicher** | IT-Leitung |\n"
"| **Datentypen** | Dokumente, E-Mails |\n"
"| **Risikoklasse** | Minimal |\n"
"| **Status** | Aktiv, genehmigt |\n"
"| **Letzte Pr\u00fcfung** | 2025-01-15 |\n\n"
"## 4-Schritt-Methodik\n\n"
"### Schritt 1: Abteilungsbefragung\n"
"Standardisierter Fragebogen an alle Abteilungsleiter. "
"Frage: *Welche Tools mit KI-Funktionen nutzt Ihr Team?*\n\n"
"### Schritt 2: Tech-Stack-Analyse\n"
"IT pr\u00fcft alle aktiven SaaS-Lizenzen auf KI-Features.\n\n"
"### Schritt 3: Dienstleister-Audit\n"
"Externe Partner befragen: *Setzen Sie KI in unseren Projekten ein?*\n\n"
"### Schritt 4: Konsolidierung\n"
"Alle Ergebnisse in zentrales Register \u00fcberf\u00fchren. Dubletten bereinigen.\n\n"
"> Tipp: Starten Sie mit den 10 meistgenutzten Tools \u2014 nicht mit allem gleichzeitig.\n"
},
{"title": "Risikoklassifizierung in der Praxis", "ordering": 2, "duration": 8, "content":
"# Risikoklassifizierung in der Praxis\n\n"
"## Der Entscheidungsbaum\n\n"
"F\u00fcr jedes KI-System im Inventar:\n\n"
"**Frage 1:** Trifft das System automatisierte Entscheidungen \u00fcber Personen?\n"
"- Ja \u2192 Weiter zu Frage 2\n"
"- Nein \u2192 Wahrscheinlich *Minimales Risiko*\n\n"
"**Frage 2:** Betrifft es einen Hochrisiko-Bereich (Personal, Kredit, Bildung, Gesundheit)?\n"
"- Ja \u2192 **Hohes Risiko**\n"
"- Nein \u2192 Weiter zu Frage 3\n\n"
"**Frage 3:** Interagiert es direkt mit Nutzern (Chatbot, Empfehlung)?\n"
"- Ja \u2192 **Begrenztes Risiko** (Transparenzpflicht)\n"
"- Nein \u2192 **Minimales Risiko**\n\n"
"## Praxisbeispiele\n\n"
"| KI-System | Risikoklasse | Begr\u00fcndung |\n"
"|-----------|-------------|------------|\n"
"| ChatGPT f\u00fcr Texte | Begrenzt | Chatbot, Transparenzpflicht |\n"
"| KI-Bewerber-Screening | **Hoch** | Personalentscheidung |\n"
"| Spam-Filter | Minimal | Keine Personenentscheidung |\n"
"| Predictive Maintenance | Minimal | Kein Personenbezug |\n"
"| KI-Kreditscoring | **Hoch** | Finanzentscheidung |\n"
"| Copilot f\u00fcr Code | Begrenzt | Produktivit\u00e4tstool |\n\n"
"## Dokumentationspflichten bei Hochrisiko\n\n"
"1. Technische Dokumentation des Systems\n"
"2. Risikomanagement-System einrichten\n"
"3. Datenqualit\u00e4ts-Management nachweisen\n"
"4. Menschliche Aufsicht sicherstellen\n"
"5. Logging und Nachvollziehbarkeit gew\u00e4hrleisten\n"
},
{"title": "Das lebendige Register: Pflege und Updates", "ordering": 3, "duration": 6, "content":
"# Das lebendige Register\n\n"
"Ein KI-Inventar ist nur n\u00fctzlich, wenn es aktuell bleibt.\n\n"
"## Trigger f\u00fcr Updates\n\n"
"- **Neues Tool:** Jede KI-Beschaffung muss ins Register\n"
"- **Neues Feature:** SaaS-Updates mit KI-Funktionen pr\u00fcfen\n"
"- **Neuer Dienstleister:** KI-Einsatz vertraglich kl\u00e4ren\n"
"- **Vorfall:** Jeder KI-bezogene Vorfall dokumentieren\n"
"- **Regulierung:** Neue Anforderungen gegen Register pr\u00fcfen\n\n"
"## Der monatliche KI-Check (15 Min.)\n\n"
"1. Neue KI-Tools in den letzten 30 Tagen?\n"
"2. Bestehende Tools mit neuen KI-Features?\n"
"3. KI-bezogene Vorf\u00e4lle?\n"
"4. Regulatorische Neuigkeiten?\n"
"5. Offene Maßnahmen aus letztem Review?\n\n"
"## Verantwortlichkeiten\n\n"
"| Rolle | Aufgabe |\n"
"|-------|--------|\n"
"| **KI-Beauftragter** | Register pflegen, Reviews koordinieren |\n"
"| **IT-Leitung** | Tech-Stack monitoren, Freigaben erteilen |\n"
"| **DSB** | Datenschutz-Bewertungen durchf\u00fchren |\n"
"| **Abteilungsleiter** | Neue KI-Nutzung melden |\n"
"| **Gesch\u00e4ftsf\u00fchrung** | Strategie, Budget, Eskalationen |\n\n"
"> Ein Inventar, das nicht gepflegt wird, ist gef\u00e4hrlicher als keins \u2014 "
"weil es falsche Sicherheit suggeriert.\n"
},
],
},
{
"title": "KI-Governance aufbauen \u2014 Strukturen f\u00fcr souver\u00e4nen KI-Einsatz",
"description": "Richtlinien, Freigabeprozesse, Rollen und die KI-Nutzungsrichtlinie.",
"ordering": 7,
"lessons": [
{"title": "Die KI-Nutzungsrichtlinie erstellen", "ordering": 1, "duration": 8, "content":
"# Die KI-Nutzungsrichtlinie\n\n"
"Eine KI-Nutzungsrichtlinie ist das zentrale Governance-Dokument.\n\n"
"## Gliederung (Template)\n\n"
"### 1. Geltungsbereich\n"
"F\u00fcr wen gilt die Richtlinie? Alle Mitarbeiter, externe Dienstleister?\n\n"
"### 2. Erlaubte KI-Nutzung\n"
"- Genehmigte Tools und Einsatzzwecke\n"
"- Welche Daten d\u00fcrfen eingegeben werden?\n"
"- Welche Daten d\u00fcrfen *nicht* eingegeben werden?\n\n"
"### 3. Verbotene KI-Nutzung\n"
"- Keine personenbezogenen Daten in nicht-freigegebene Tools\n"
"- Keine automatisierten Personalentscheidungen ohne menschliche Pr\u00fcfung\n"
"- Keine KI-generierten Inhalte ohne Kennzeichnung\n\n"
"### 4. Freigabeprozess\n"
"Wie werden neue KI-Tools beantragt und freigegeben?\n\n"
"### 5. Verantwortlichkeiten\n"
"Wer ist KI-Beauftragter? Wer genehmigt? Wer dokumentiert?\n\n"
"### 6. Vorfallmanagement\n"
"Was tun bei KI-Pannen? Meldewege, Eskalation.\n\n"
"### 7. Schulungspflichten\n"
"Welche Schulungen sind f\u00fcr wen verpflichtend?\n\n"
"### 8. \u00dcberpr\u00fcfung\n"
"Wann wird die Richtlinie aktualisiert? (Mind. j\u00e4hrlich)\n\n"
"> **Praxis-Tipp:** Starten Sie mit 2 Seiten. Besser eine kurze Richtlinie, "
"die gelesen wird, als eine umfassende, die in der Schublade liegt.\n"
},
{"title": "Freigabeprozess f\u00fcr neue KI-Tools", "ordering": 2, "duration": 7, "content":
"# Freigabeprozess f\u00fcr neue KI-Tools\n\n"
"## Der 5-Schritt-Prozess\n\n"
"### Schritt 1: Antrag\n"
"Mitarbeiter f\u00fcllt KI-Tool-Antrag aus:\n"
"- Welches Tool? Welcher Anbieter?\n"
"- Wof\u00fcr? Welche Daten?\n"
"- Welcher Mehrwert?\n\n"
"### Schritt 2: Vorpr\u00fcfung (IT)\n"
"- Technische Kompatibilit\u00e4t\n"
"- Sicherheitsstandards\n"
"- Bestehende Alternativen?\n\n"
"### Schritt 3: Risikobewertung\n"
"- Risikoklasse nach EU AI Act\n"
"- Datenschutz-Folgenabsch\u00e4tzung (falls n\u00f6tig)\n"
"- R\u00b3-Raster-Bewertung\n\n"
"### Schritt 4: Entscheidung\n"
"- Minimales Risiko: IT-Leitung genehmigt\n"
"- Begrenztes Risiko: IT + DSB genehmigen\n"
"- Hohes Risiko: Gesch\u00e4ftsf\u00fchrung entscheidet\n\n"
"### Schritt 5: Onboarding\n"
"- Ins KI-Register aufnehmen\n"
"- Schulung f\u00fcr Nutzer\n"
"- Review-Termin setzen (nach 3 Monaten)\n\n"
"## Zeitrahmen\n\n"
"| Risikoklasse | Max. Bearbeitungszeit |\n"
"|-------------|---------------------|\n"
"| Minimal | 5 Arbeitstage |\n"
"| Begrenzt | 10 Arbeitstage |\n"
"| Hoch | 20 Arbeitstage |\n"
},
{"title": "Governance-Rollen und Verantwortlichkeiten", "ordering": 3, "duration": 7, "content":
"# Governance-Rollen\n\n"
"## Die 5 Schl\u00fcsselrollen\n\n"
"### 1. KI-Beauftragter (AI Officer)\n"
"- KI-Register pflegen\n"
"- Freigabeprozess koordinieren\n"
"- Schulungen organisieren\n"
"- Quartals-Reviews durchf\u00fchren\n"
"- **Zeitaufwand:** 2\u20134 Std./Woche (bei KMU)\n\n"
"### 2. Gesch\u00e4ftsf\u00fchrung\n"
"- KI-Strategie verantworten\n"
"- Budget freigeben\n"
"- Hochrisiko-Entscheidungen treffen\n"
"- Governance vorleben\n\n"
"### 3. IT-Leitung\n"
"- Technische Bewertung neuer Tools\n"
"- Sicherheitsstandards durchsetzen\n"
"- Monitoring und Logging\n\n"
"### 4. Datenschutzbeauftragter\n"
"- DSGVO-Konformit\u00e4t pr\u00fcfen\n"
"- Datenschutz-Folgenabsch\u00e4tzungen\n"
"- Betroffenenrechte sicherstellen\n\n"
"### 5. Abteilungsleiter\n"
"- Neue KI-Nutzung melden\n"
"- Richtlinie im Team durchsetzen\n"
"- Schulungsteilnahme sicherstellen\n\n"
"## F\u00fcr KMU: Rollen kombinieren\n\n"
"In kleinen Unternehmen k\u00f6nnen Rollen zusammengefasst werden:\n"
"- **< 50 Mitarbeiter:** GF + IT-Leitung + DSB reichen\n"
"- **50\u2013200 Mitarbeiter:** Zus\u00e4tzlich KI-Beauftragter (Teilzeit)\n"
"- **> 200 Mitarbeiter:** Dedizierter KI-Beauftragter empfohlen\n\n"
"> Governance braucht keine neue Abteilung \u2014 sie braucht klare Zust\u00e4ndigkeiten.\n"
},
],
},
{
"title": "KI-Kompetenz aufbauen \u2014 Das Team mitnehmen",
"description": "Rollenbasierte Lernpfade, Kompetenznachweis, Art. 4 Compliance.",
"ordering": 8,
"lessons": [
{"title": "Lernpfade nach Rolle gestalten", "ordering": 1, "duration": 8, "content":
"# Lernpfade nach Rolle\n\n"
"Art. 4 EU AI Act fordert \u201eausreichende KI-Kompetenz\u201c \u2014 "
"aber was hei\u00dft das f\u00fcr verschiedene Rollen?\n\n"
"## Lernpfad 1: Gesch\u00e4ftsf\u00fchrung\n\n"
"**Ziel:** Strategische KI-Entscheidungen treffen k\u00f6nnen\n\n"
"| Modul | Dauer | Inhalt |\n"
"|-------|-------|--------|\n"
"| KI-Grundlagen | 60 Min. | Was ist KI? Chancen und Risiken |\n"
"| EU AI Act | 90 Min. | Pflichten, Risikoklassen, Haftung |\n"
"| KI-Strategie | 60 Min. | D4-Modell, Reifegradbestimmung |\n"
"| Governance | 60 Min. | Richtlinien, Rollen, Prozesse |\n\n"
"## Lernpfad 2: IT-Leitung / DSB\n\n"
"**Ziel:** KI-Systeme bewerten und \u00fcberwachen k\u00f6nnen\n\n"
"| Modul | Dauer | Inhalt |\n"
"|-------|-------|--------|\n"
"| KI-Technologie | 120 Min. | ML, LLMs, Embeddings, APIs |\n"
"| Risikobewertung | 90 Min. | R\u00b3-Raster, EU AI Act-Klassifizierung |\n"
"| Datenschutz & KI | 90 Min. | DSGVO Art. 22, DSFA, Auftragsverarbeitung |\n"
"| Monitoring | 60 Min. | Logging, Bias-Detection, Drift |\n\n"
"## Lernpfad 3: Fachabteilung\n\n"
"**Ziel:** KI sicher und verantwortungsvoll nutzen\n\n"
"| Modul | Dauer | Inhalt |\n"
"|-------|-------|--------|\n"
"| KI im Alltag | 30 Min. | Was darf ich? Was nicht? |\n"
"| Datensicherheit | 30 Min. | Welche Daten eingeben? |\n"
"| Prompt-Qualit\u00e4t | 30 Min. | Bessere Ergebnisse erzielen |\n"
"| Meldepflichten | 30 Min. | Wann melden? An wen? |\n"
},
{"title": "Kompetenznachweis und Dokumentation", "ordering": 2, "duration": 7, "content":
"# Kompetenznachweis\n\n"
"Art. 4 fordert nachweisbare Kompetenz \u2014 nicht nur Teilnahme.\n\n"
"## 3 Stufen des Nachweises\n\n"
"### Stufe 1: Teilnahmenachweis\n"
"- Unterschriftenliste / digitales Tracking\n"
"- *Minimum* f\u00fcr Art. 4, aber nicht ausreichend\n\n"
"### Stufe 2: Wissenstest\n"
"- Multiple-Choice nach jeder Schulung\n"
"- Mindestens 70 % zum Bestehen\n"
"- Dokumentation der Ergebnisse\n\n"
"### Stufe 3: Kompetenznachweis\n"
"- Praktische Aufgabe (z.B. Risikobewertung eines realen Systems)\n"
"- Peer-Review oder Vorgesetzten-Best\u00e4tigung\n"
"- **Goldstandard** f\u00fcr Art. 4\n\n"
"## Dokumentation\n\n"
"F\u00fcr jede Person dokumentieren:\n"
"- Welche Schulungen absolviert?\n"
"- Wann? (Datum)\n"
"- Ergebnis? (Bestanden/Nicht bestanden)\n"
"- N\u00e4chster Refresher? (Datum)\n"
"- Rolle im KI-Kontext?\n\n"
"## Revisionssicherheit\n\n"
"- Digitale Dokumentation bevorzugen\n"
"- Mindestens 3 Jahre aufbewahren\n"
"- Zugang f\u00fcr Aufsichtsbeh\u00f6rden sicherstellen\n\n"
"> Ein Ordner mit Teilnahmelisten ist kein Kompetenznachweis.\n"
},
{"title": "Change Management f\u00fcr KI-Kompetenz", "ordering": 3, "duration": 7, "content":
"# Change Management f\u00fcr KI-Kompetenz\n\n"
"## Die 4 Widerstandstypen\n\n"
"### 1. Die Skeptiker\n"
"\u201eBrauchen wir nicht.\u201c\n"
"**Strategie:** Konkrete Use Cases zeigen, die ihr Team betreffen.\n\n"
"### 2. Die \u00dcberforderten\n"
"\u201eIch verstehe das nicht.\u201c\n"
"**Strategie:** Niedrigschwellige Einstiege. 30-Minuten-Module, kein Fachjargon.\n\n"
"### 3. Die Enthusiasten\n"
"\u201eIch nutze schon alles!\u201c\n"
"**Strategie:** Zu KI-Champions machen. Peer-Teaching f\u00f6rdern.\n\n"
"### 4. Die Gleichg\u00fcltigen\n"
"\u201eIst mir egal.\u201c\n"
"**Strategie:** Verpflichtende Mindest-Schulung. Relevanz f\u00fcr eigene Rolle zeigen.\n\n"
"## 5 Erfolgsfaktoren\n\n"
"1. **F\u00fchrung geht voran:** GF macht Schulung zuerst und \u00f6ffentlich\n"
"2. **Kleine Schritte:** 30 Min./Woche statt ganzer Schulungstag\n"
"3. **Praxisbezug:** Echte Tools, echte Aufgaben, eigene Abteilung\n"
"4. **Peer-Learning:** KI-Champions in jeder Abteilung\n"
"5. **Feiern:** Erfolge sichtbar machen, Zertifikate, Anerkennung\n\n"
"> KI-Kompetenz ist keine Schulung \u2014 sie ist ein Kulturwandel.\n"
},
],
},
{
"title": "Vom Kontrollverlust zur Gestaltungsmacht",
"description": "KI-Souver\u00e4nit\u00e4t als F\u00fchrungsaufgabe \u2014 der Weg nach vorn.",
"ordering": 9,
"lessons": [
{"title": "KI-Souver\u00e4nit\u00e4t als F\u00fchrungsaufgabe", "ordering": 1, "duration": 7, "content":
"# KI-Souver\u00e4nit\u00e4t als F\u00fchrungsaufgabe\n\n"
"## Die drei Ebenen der F\u00fchrung in der KI-\u00c4ra\n\n"
"### Ebene 1: Pers\u00f6nliche Souver\u00e4nit\u00e4t\n"
"- Eigenes KI-Nutzungsverhalten reflektieren\n"
"- Kognitive Fallen kennen und aktiv gegensteuern\n"
"- Eigene Urteilsf\u00e4higkeit st\u00e4rken\n\n"
"### Ebene 2: Organisationale Souver\u00e4nit\u00e4t\n"
"- Governance-Strukturen aufbauen\n"
"- KI-Inventar und Risikoklassifizierung pflegen\n"
"- Team-Kompetenz entwickeln\n\n"
"### Ebene 3: Strategische Souver\u00e4nit\u00e4t\n"
"- KI als strategisches Werkzeug positionieren\n"
"- Chancen erkennen, ohne Risiken zu ignorieren\n"
"- Innovation und Kontrolle balancieren\n\n"
"## Die F\u00fchrungskraft als KI-Gestalter\n\n"
"| Gestern | Heute | Morgen |\n"
"|---------|-------|--------|\n"
"| KI ist IT-Thema | KI ist Chefsache | KI ist Kulturfrage |\n"
"| Reagieren | Regulieren | Gestalten |\n"
"| Angst oder Ignoranz | Verstehen | Souver\u00e4n nutzen |\n\n"
"> KI-Souver\u00e4nit\u00e4t beginnt bei Ihnen selbst.\n"
},
{"title": "Der 12-Monats-Fahrplan", "ordering": 2, "duration": 8, "content":
"# Der 12-Monats-Fahrplan\n\n"
"## Quartal 1: Fundament (Monat 1\u20133)\n"
"- [ ] KI-Inventar erstellen (vollst\u00e4ndig)\n"
"- [ ] Risikoklassifizierung durchf\u00fchren\n"
"- [ ] KI-Nutzungsrichtlinie verabschieden\n"
"- [ ] KI-Beauftragten benennen\n"
"- [ ] Erste Schulung: Gesch\u00e4ftsf\u00fchrung\n\n"
"## Quartal 2: Struktur (Monat 4\u20136)\n"
"- [ ] Freigabeprozess etablieren\n"
"- [ ] Schulungen: IT-Leitung + DSB\n"
"- [ ] Schulungen: Fachabteilungen (Pilot)\n"
"- [ ] Hochrisiko-Systeme dokumentieren\n"
"- [ ] Erster Quartals-Review\n\n"
"## Quartal 3: Durchdringung (Monat 7\u20139)\n"
"- [ ] Schulungen: Alle Mitarbeiter\n"
"- [ ] KI-Champions in Abteilungen\n"
"- [ ] Kompetenznachweis-System einf\u00fchren\n"
"- [ ] Vorfall-Management testen\n"
"- [ ] Zweiter Quartals-Review\n\n"
"## Quartal 4: Reife (Monat 10\u201312)\n"
"- [ ] Dritter Quartals-Review\n"
"- [ ] Governance-Richtlinie aktualisieren\n"
"- [ ] Refresher-Schulungen planen\n"
"- [ ] KPI-Reporting aufbauen\n"
"- [ ] Strategie-Update: KI-Roadmap f\u00fcr n\u00e4chstes Jahr\n\n"
"## Erfolgs-KPIs\n\n"
"| KPI | Ziel nach 12 Monaten |\n"
"|-----|---------------------|\n"
"| KI-Register Vollst\u00e4ndigkeit | 100 % |\n"
"| Schulungsquote | > 90 % |\n"
"| Kompetenznachweis-Quote | > 70 % |\n"
"| Hochrisiko-Dokumentation | 100 % |\n"
"| Quartals-Reviews durchgef\u00fchrt | 4/4 |\n"
},
{"title": "Ihr n\u00e4chster Schritt", "ordering": 3, "duration": 5, "content":
"# Ihr n\u00e4chster Schritt\n\n"
"Sie haben jetzt das Wissen. Die Frage ist: **Was tun Sie morgen fr\u00fch?**\n\n"
"## Die Montag-Morgen-Aufgabe\n\n"
"W\u00e4hlen Sie **eine** Ma\u00dfnahme \u2014 die kleinste, die den gr\u00f6\u00dften Effekt hat:\n\n"
"### Wenn Sie noch nie \u00fcber KI-Governance nachgedacht haben:\n"
"\u2192 Schreiben Sie eine E-Mail an Ihre Abteilungsleiter: "
"*\u201eWelche KI-Tools nutzt Ihr Team? Bitte bis Freitag antworten.\u201c*\n\n"
"### Wenn Sie schon ein KI-Inventar haben:\n"
"\u2192 Klassifizieren Sie Ihre Top-5-Systeme nach EU AI Act-Risikoklassen.\n\n"
"### Wenn Sie schon eine Richtlinie haben:\n"
"\u2192 Planen Sie den ersten Quartals-Review. 90 Minuten. N\u00e4chste Woche.\n\n"
"### Wenn Sie schon Schulungen durchf\u00fchren:\n"
"\u2192 F\u00fchren Sie einen Kompetenznachweis ein. Test statt nur Teilnahmebest\u00e4tigung.\n\n"
"## Zusammenfassung des Kurses\n\n"
"| Kapitel | Kernbotschaft |\n"
"|---------|---------------|\n"
"| 1. Shadow AI | KI ist schon da \u2014 sehen Sie hin |\n"
"| 2. Kognitive Fallen | Kennen Sie Ihre Verzerrungen |\n"
"| 3. EU AI Act | Regulierung ist Chance, nicht Last |\n"
"| 4. D4-Modell | Vier Dimensionen systematisch entwickeln |\n"
"| 5. R\u00b3-Raster | Risiken erkennen, bewerten, reagieren |\n"
"| 6. KI-Inventar | Wissen, was l\u00e4uft |\n"
"| 7. Governance | Strukturen schaffen |\n"
"| 8. KI-Kompetenz | Team mitnehmen |\n"
"| 9. Gestaltungsmacht | F\u00fchren in der KI-\u00c4ra |\n\n"
"> **KI-Souver\u00e4nit\u00e4t ist kein Zustand \u2014 es ist eine Reise. "
"Sie haben den ersten Schritt gemacht.**\n"
},
],
},
]
# fmt: on
