# Generated by Django 5.2.12 on 2026-03-12 18:42

import django.db.models.deletion
import iil_learnfw.models.course
import iil_learnfw.models.scorm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('course_completed', 'Course Completed'), ('quiz_passed', 'Quiz Passed'), ('streak_reached', 'Streak Reached'), ('points_reached', 'Points Reached'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('threshold', models.PositiveIntegerField(default=1, help_text='Threshold for auto-award (e.g. 5 courses, 100 points).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('name', models.CharField(max_length=200)),
                ('html_template', models.TextField(help_text='HTML template for WeasyPrint rendering. Available context: {{ user }}, {{ course }}, {{ issued_at }}.')),
                ('logo', models.FileField(blank=True, upload_to=iil_learnfw.models.course.tenant_upload_path)),
                ('signature_image', models.FileField(blank=True, upload_to=iil_learnfw.models.course.tenant_upload_path)),
                ('valid_for_days', models.PositiveIntegerField(blank=True, help_text='Certificate validity in days (NULL = no expiry).', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for courses without explicit template.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('first_login', 'First Login'), ('role_change', 'Role Change'), ('manual', 'Manual Assignment')], default='first_login', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('free_text', 'Free Text'), ('matching', 'Matching')], default='single_choice', max_length=20)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Shown after answering.')),
                ('points', models.PositiveIntegerField(default=1)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=iil_learnfw.models.course.tenant_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='If True, visible to ALL tenants (platform-wide content).')),
                ('module_code', models.CharField(blank=True, help_text='billing-hub ModuleSubscription code for marketplace courses.', max_length=50)),
                ('marketplace_enabled', models.BooleanField(default=False)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('passing_score', models.PositiveIntegerField(default=80, help_text='Minimum score (%) to pass.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_courses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='iil_learnfw.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='iil_learnfw.course')),
            ],
            options={
                'ordering': ['ordering'],
                'unique_together': {('course', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('title', models.CharField(max_length=300)),
                ('content_type', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('external', 'External URL')], default='markdown', max_length=20)),
                ('content_text', models.TextField(blank=True, help_text='Markdown content (when content_type=markdown).')),
                ('content_file', models.FileField(blank=True, help_text='PDF or PPTX file.', upload_to=iil_learnfw.models.course.tenant_upload_path)),
                ('external_url', models.URLField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=5)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='iil_learnfw.chapter')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('points', models.IntegerField(help_text='Positive = award, negative = deduction.')),
                ('reason', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('lesson', 'Lesson Completed'), ('quiz', 'Quiz Passed'), ('badge', 'Badge Awarded'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='iil_learnfw.question')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('title', models.CharField(max_length=300)),
                ('passing_score', models.PositiveIntegerField(default=80, help_text='Minimum score (%) to pass.')),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = unlimited attempts.')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (NULL = no limit).', null=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='iil_learnfw.chapter')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='iil_learnfw.course')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='iil_learnfw.quiz'),
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_steps', to='iil_learnfw.course')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='iil_learnfw.onboardingflow')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_steps', to='iil_learnfw.quiz')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score as percentage (0-100).', max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='iil_learnfw.quiz')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScormPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('scorm_version', models.CharField(choices=[('1.2', 'SCORM 1.2'), ('2004', 'SCORM 2004')], default='1.2', max_length=4)),
                ('package_file', models.FileField(upload_to=iil_learnfw.models.scorm.scorm_upload_path)),
                ('manifest', models.JSONField(blank=True, default=dict, help_text='Parsed imsmanifest.xml as JSON.')),
                ('entry_point', models.CharField(blank=True, help_text='Relative path to launch file within package.', max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_packages', to='iil_learnfw.course')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user points',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='iil_learnfw.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public verification token (non-PK UUID, ADR-022).', unique=True)),
                ('pdf_file', models.FileField(blank=True, upload_to=iil_learnfw.models.course.tenant_upload_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='iil_learnfw.course')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='iil_learnfw.certificatetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('free_text', models.TextField(blank=True, help_text='Free text response.')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='iil_learnfw.attempt')),
                ('selected_answer', models.ForeignKey(blank=True, help_text='Selected answer (MC/SC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_selections', to='iil_learnfw.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='iil_learnfw.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ScormTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('status', models.CharField(choices=[('not_attempted', 'Not Attempted'), ('incomplete', 'Incomplete'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_attempted', max_length=20)),
                ('score_raw', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(default=0)),
                ('score_max', models.FloatField(default=100)),
                ('total_time', models.DurationField(blank=True, help_text='Total time spent in SCORM session.', null=True)),
                ('suspend_data', models.TextField(blank=True, help_text='SCORM suspend_data for session resume.')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='iil_learnfw.scormpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_scorm_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'package')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='iil_learnfw.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='iil_learnfw.onboardingflow')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='iil_learnfw.onboardingstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_onboarding_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'step')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID (NULL = single-tenant mode or global content).', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='iil_learnfw.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnfw_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
